[package]
name = "e3-graph"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
ae-common.workspace = true
ae-wal.workspace = true
ae-kernel.workspace = true
ae-telemetry.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
