"""PostgreSQL structured logs, committed independently of business transactions.

Uses PostgreSQL queries explicitly; no SQLite connection, file or SQL adapter is
created. Redaction and span contracts are shared with the engineering log store.
"""

from __future__ import annotations

import json
import logging
import secrets
import sys
from collections.abc import Iterator
from contextlib import contextmanager
from datetime import UTC, datetime, timedelta
from pathlib import Path
from threading import RLock
from typing import Any

from aether_agent_memory.runtime.contracts.models import TrustedContext

from .common import now
from .telemetry import Telemetry


class _PoolLogRedaction(logging.Filter):
    """Pool worker logs bypass our exception handlers and may contain libpq data."""

    def filter(self, record: logging.LogRecord) -> bool:
        record.msg = "P3_POSTGRES_POOL_EVENT"
        record.args = ()
        record.exc_info = None
        record.exc_text = None
        record.stack_info = None
        return True


_pool_log_redaction = _PoolLogRedaction()


class PostgresTelemetry(Telemetry):
    backend = "postgresql"

    def __init__(
        self,
        dsn: str,
        local_path: str | Path,
        *,
        retention_days: int = 14,
        max_records: int = 200_000,
    ) -> None:
        if retention_days < 1 or max_records < 100:
            raise ValueError("invalid log retention")
        try:
            from psycopg.conninfo import conninfo_to_dict
            from psycopg_pool import ConnectionPool
        except ImportError:
            raise RuntimeError("PostgreSQL logs require psycopg and psycopg_pool") from None

        # Kept solely for callers' local runtime metadata. Never open this path.
        self.path = Path(local_path)
        self.retention_days, self.max_records = retention_days, max_records
        self.instance_id = secrets.token_hex(8)
        self.dropped = 0
        self.last_error: str | None = None
        self._writes = 0
        self.tracer = None
        self._lock = RLock()
        try:
            values = conninfo_to_dict(dsn)
            # A desktop relay can need several TLS round trips. Honor the
            # explicit deployment budget while keeping startup bounded.
            connect_timeout = max(3, min(60, int(values.get("connect_timeout") or 3)))
        except Exception:
            raise ValueError("invalid PostgreSQL log connection configuration") from None
        # Apply at the originating logger, before any application/root handlers.
        # Sanitize every psycopg pool event: rollback/reset errors may lack a
        # pool name, and message-based secret matching is not reliable.
        logging.getLogger("psycopg.pool").addFilter(_pool_log_redaction)
        self._pool = ConnectionPool(
            dsn,
            # Health concurrently emits one span per registered probe, alongside
            # Activity and HTTP spans. Cold TLS connections cannot grow within
            # the short checkout budget, so reserve the bounded burst capacity.
            min_size=16,
            max_size=16,
            num_workers=8,
            timeout=0.25,
            max_waiting=16,
            kwargs={"connect_timeout": connect_timeout},
            configure=self._configure,
            name="p3-logs",
            open=False,
        )
        try:
            self._pool.open(wait=True, timeout=max(5, connect_timeout + 5))
            with self.connect() as db:
                # Serialize first-time DDL across independent API/worker starts.
                db.execute("SELECT pg_advisory_xact_lock(68431290713021)")
                db.execute(
                    "CREATE TABLE IF NOT EXISTS node_logs ("
                    "sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    "occurred_at TEXT NOT NULL, trace_id TEXT NOT NULL, "
                    "principal_id TEXT NOT NULL, scope TEXT NOT NULL, "
                    "span_id TEXT NOT NULL, phase TEXT NOT NULL, data TEXT NOT NULL "
                    "CHECK (jsonb_typeof(data::jsonb) = 'object'))"
                )
                for statement in (
                    "CREATE INDEX IF NOT EXISTS logs_trace ON node_logs"
                    "(trace_id,principal_id,scope,sequence)",
                    "CREATE INDEX IF NOT EXISTS logs_age ON node_logs(occurred_at)",
                    "CREATE INDEX IF NOT EXISTS logs_catalog ON node_logs"
                    "(principal_id,scope,trace_id,sequence,occurred_at,span_id,phase,"
                    "((data::jsonb -> 'contract' ->> 'flow')))",
                    "CREATE TABLE IF NOT EXISTS log_meta(key TEXT PRIMARY KEY,value TEXT)",
                ):
                    db.execute(statement)
            self.prune()
        except Exception:
            self._pool.close()
            raise RuntimeError("PostgreSQL log store initialization failed") from None

    @staticmethod
    def _configure(db: Any) -> None:
        # Every statement and checkout is bounded, including logging on a request
        # thread. The read snapshot uses another pooled connection, with no writer
        # mutex held by a dashboard request.
        db.execute("SET statement_timeout = '1000ms'")
        db.execute("SET lock_timeout = '250ms'")
        db.execute("SET idle_in_transaction_session_timeout = '30s'")
        db.commit()

    @contextmanager
    def connect(self) -> Iterator[Any]:
        with self._pool.connection() as db, db.transaction():
            yield db

    @contextmanager
    def reader(self) -> Iterator[Any]:
        with self.connect() as db:
            db.execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY")
            yield db

    def close(self) -> None:
        self._pool.close()

    def probe(self, *, write: bool = False) -> dict[str, Any]:
        with self.connect() as db:
            db.execute("SELECT sequence FROM node_logs LIMIT 1").fetchone()
            if write:
                with db.transaction(force_rollback=True):
                    key = "__p3_probe_" + secrets.token_hex(16)
                    db.execute("INSERT INTO log_meta(key,value) VALUES (%s,'probe')", (key,))
                    row = db.execute("SELECT value FROM log_meta WHERE key=%s", (key,)).fetchone()
                    if row != ("probe",):
                        raise RuntimeError("PostgreSQL log probe mismatch")
        return {
            "state": "available",
            "reason": "write_rollback" if write else "read_ok",
            "backend": self.backend,
        }

    def retained_bounds(self, db: Any) -> tuple[int, str]:
        row = db.execute(
            "SELECT sequence FROM node_logs ORDER BY sequence DESC LIMIT 1 OFFSET %s",
            (self.max_records,),
        ).fetchone()
        cutoff = (datetime.now(UTC) - timedelta(days=self.retention_days)).isoformat()
        return (row[0] if row else 0), cutoff

    def prune(self) -> None:
        cutoff = (datetime.now(UTC) - timedelta(days=self.retention_days)).isoformat()
        with self.connect() as db:
            deleted = db.execute("DELETE FROM node_logs WHERE occurred_at < %s", (cutoff,)).rowcount
            deleted += db.execute(
                "DELETE FROM node_logs WHERE sequence <= "
                "(SELECT sequence FROM node_logs ORDER BY sequence DESC LIMIT 1 OFFSET %s)",
                (self.max_records,),
            ).rowcount
            if deleted:
                db.execute(
                    "INSERT INTO log_meta(key,value) VALUES ('last_pruned_at',%s) "
                    "ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value",
                    (now(),),
                )

    def _write(self, ctx: TrustedContext, data: dict[str, Any]) -> None:
        try:
            encoded = json.dumps(data, ensure_ascii=False, allow_nan=False)
            if len(encoded.encode("utf-8")) > 32_768:
                data.pop("input", None)
                data.pop("output", None)
                data["detail_truncated"] = True
                encoded = json.dumps(data, ensure_ascii=False, allow_nan=False)
                if len(encoded.encode("utf-8")) > 32_768:
                    raise ValueError("oversized node log")
            with self.connect() as db:
                db.execute(
                    "INSERT INTO node_logs(occurred_at,trace_id,principal_id,scope,"
                    "span_id,phase,data) VALUES (%s,%s,%s,%s,%s,%s,%s)",
                    (
                        data["occurred_at"],
                        ctx.trace_id,
                        ctx.principal.principal_id,
                        ctx.principal.home_scope.model_dump_json(),
                        data["span_id"],
                        data["phase"],
                        encoded,
                    ),
                )
            with self._lock:
                self._writes += 1
                prune = self._writes % 100 == 0
                self.last_error = None
            if prune:
                self.prune()
        except Exception as exc:
            # Includes pool exhaustion/closure and statement timeouts. Telemetry
            # must never turn a committed external effect into a business retry.
            # Exception messages and connection strings are deliberately excluded.
            with self._lock:
                self.dropped += 1
                self.last_error = type(exc).__name__
                first = self.dropped == 1
            if first:
                print('{"level":"ERROR","code":"P3_LOG_WRITE_FAILED"}', file=sys.stderr)

    def traces(
        self,
        ctx: TrustedContext,
        *,
        before: int | None = None,
        limit: int = 50,
        flow: str | None = None,
    ) -> dict[str, Any]:
        if not 1 <= limit <= 100 or (before is not None and before < 1):
            raise ValueError("invalid trace page")
        if flow not in {None, "business", "remember", "recall", "operate", "runtime"}:
            raise ValueError("invalid trace flow")
        with self.reader() as db:
            floor, cutoff = self.retained_bounds(db)
            # Parameter types are explicit for PostgreSQL's nullable bind values.
            rows = db.execute(
                "SELECT trace_id, MIN(sequence), MIN(occurred_at), MAX(occurred_at), "
                "COUNT(*), COUNT(DISTINCT span_id), "
                "COUNT(DISTINCT CASE WHEN phase='failed' THEN span_id END) "
                "FROM node_logs WHERE principal_id=%s AND scope=%s "
                "AND sequence>%s AND occurred_at>=%s "
                "GROUP BY trace_id HAVING (%s::bigint IS NULL OR MIN(sequence) < %s) "
                "AND (%s::text IS NULL OR BOOL_OR("
                "data::jsonb -> 'contract' ->> 'flow' = %s OR "
                "(%s='business' AND data::jsonb -> 'contract' ->> 'flow' "
                "IN ('remember','recall','operate')))) "
                "ORDER BY MIN(sequence) DESC LIMIT %s",
                (
                    ctx.principal.principal_id,
                    ctx.principal.home_scope.model_dump_json(),
                    floor,
                    cutoff,
                    before,
                    before,
                    flow,
                    flow,
                    flow,
                    limit + 1,
                ),
            ).fetchall()
            items = []
            for trace_id, first, started, last, records, spans, failed in rows[:limit]:
                raw = db.execute(
                    "SELECT data FROM node_logs WHERE sequence=%s", (first,)
                ).fetchone()
                contract = json.loads(raw[0]).get("contract", {})
                items.append(
                    {
                        "trace_id": trace_id,
                        "first_sequence": first,
                        "started_at": started,
                        "last_seen": last,
                        "record_count": records,
                        "span_count": spans,
                        "failed_span_count": failed,
                        "entry_node": contract.get("node", "unknown"),
                        "flow": contract.get("flow", "runtime"),
                    }
                )
        return {
            "items": items,
            "next_before": rows[limit - 1][1] if len(rows) > limit else None,
            "coverage": "retained_records_only",
        }

    def page(
        self, ctx: TrustedContext, trace_id: str, *, after: int = 0, limit: int = 100
    ) -> dict[str, Any]:
        if not 1 <= limit <= 500 or after < 0:
            raise ValueError("invalid log page")
        with self.reader() as db:
            floor, cutoff = self.retained_bounds(db)
            rows = db.execute(
                "SELECT sequence,data FROM node_logs WHERE trace_id=%s AND principal_id=%s "
                "AND scope=%s AND sequence>%s AND occurred_at>=%s ORDER BY sequence LIMIT %s",
                (
                    trace_id,
                    ctx.principal.principal_id,
                    ctx.principal.home_scope.model_dump_json(),
                    max(after, floor),
                    cutoff,
                    limit + 1,
                ),
            ).fetchall()
            pruned = db.execute("SELECT value FROM log_meta WHERE key='last_pruned_at'").fetchone()
            states = db.execute(
                "SELECT span_id, BOOL_OR(phase='started'), BOOL_OR(phase='returned'), "
                "BOOL_OR(phase='failed'), BOOL_OR(phase='cancelled') FROM node_logs "
                "WHERE trace_id=%s AND principal_id=%s AND scope=%s "
                "AND sequence>%s AND occurred_at>=%s GROUP BY span_id",
                (
                    trace_id,
                    ctx.principal.principal_id,
                    ctx.principal.home_scope.model_dump_json(),
                    floor,
                    cutoff,
                ),
            ).fetchall()
        open_spans = [s[0] for s in states if s[1] and not any(s[2:])]
        return {
            "trace_id": trace_id,
            "records": [{"sequence": seq, **json.loads(raw)} for seq, raw in rows[:limit]],
            "next_after": rows[limit - 1][0] if len(rows) > limit else None,
            "coverage": "retained_records_only",
            "last_pruned_at": pruned[0] if pruned else None,
            "local_dropped_records": self.dropped,
            "overview": {
                "span_count": len(states),
                "failed_span_count": sum(bool(s[3]) for s in states),
                "open_span_count": len(open_spans),
                "open_span_ids": open_spans[:100],
                "open_meaning": "running_or_interrupted; inspect durable task state",
            },
        }
