"""Immutable object port and our Ceph implementation, independent of P2 delivery.

Keys are logical immutable addresses generated by authorized callers. This adapter
adds an environment namespace; it does not grant tenant authorization. Remote
operations must run outside metadata transactions. A write only succeeds after
readback, including when the initial write response was lost.
"""

import asyncio
import re
from collections.abc import Callable
from typing import Protocol, TypeVar, runtime_checkable

from aether_agent_memory.remember.basic.ceph_p2 import (
    CephP2,
    CephP2Config,
    ImmutableObjectConflictError,
)
from aether_agent_memory.runtime.contracts.models import ErrorCode
from aether_agent_memory.runtime.foundation.common import FoundationError, fingerprint

T = TypeVar("T")


@runtime_checkable
class ImmutableInputObjects(Protocol):
    def put_object_sync(self, key: str, body: bytes) -> object: ...
    def get_object_sync(self, key: str) -> bytes | None: ...


@runtime_checkable
class ImmutableObjects(ImmutableInputObjects, Protocol):
    immutable_write_replay_safe: bool

    def delete_object_sync(self, key: str) -> None: ...
    def read_range_sync(self, key: str, start: int, end: int) -> bytes: ...
    async def put_object(self, key: str, body: bytes) -> None: ...
    async def get_object(self, key: str) -> bytes | None: ...
    async def delete_object(self, key: str) -> None: ...
    async def read_range(self, key: str, start: int, end: int) -> bytes: ...
    def close(self) -> None: ...


class CephObjects:
    """SigV4 and immutable writes; plaintext transport requires explicit opt-in."""

    provider_id = "ceph"
    immutable_write_replay_safe = True

    def __init__(
        self,
        config: CephP2Config,
        *,
        namespace: str,
        allow_insecure_http: bool = False,
    ) -> None:
        if not config.endpoint.startswith("https://") and allow_insecure_http is not True:
            raise ValueError("Ceph storage requires a verified HTTPS endpoint")
        if not re.fullmatch(r"[a-z0-9][a-z0-9_-]{0,63}", namespace):
            raise ValueError("Ceph namespace must be a bounded environment identifier")
        self.namespace = namespace
        self.prefix = f"aether/{namespace}/v1/"
        self.instance_id = f"{config.endpoint.rstrip('/')}/{config.bucket}/{namespace}"
        self.transport = CephP2(config)

    def binding(self) -> dict[str, str | int]:
        return {
            "provider": self.provider_id,
            "resource": fingerprint(self.instance_id),
            "namespace": self.namespace,
            "contract_version": 1,
        }

    def _key(self, key: str) -> str:
        if (
            not isinstance(key, str)
            or not key
            or "\\" in key
            or any(part in {"", ".", ".."} for part in key.split("/"))
            or any(ord(char) < 32 for char in key)
            or len((self.prefix + key).encode("utf8")) > 1024
        ):
            raise FoundationError(ErrorCode.INVALID_ARGUMENT, "invalid logical object key")
        return self.prefix + key

    @staticmethod
    def _call(operation: Callable[[], T]) -> T:
        try:
            return operation()
        except ImmutableObjectConflictError:
            raise FoundationError(
                ErrorCode.IDEMPOTENCY_CONFLICT, "immutable object already contains other bytes"
            ) from None
        except FileNotFoundError:
            raise FoundationError(ErrorCode.NOT_FOUND, "object is absent") from None
        except ValueError:
            raise FoundationError(
                ErrorCode.CONTRACT_VIOLATION, "object response failed integrity validation"
            ) from None
        except FoundationError:
            raise
        except Exception:
            raise FoundationError(
                ErrorCode.DEPENDENCY_UNAVAILABLE, "Ceph object service unavailable"
            ) from None

    def get_object_sync(self, key: str) -> bytes | None:
        address = self._key(key)
        return self._call(lambda: self.transport.get_object_sync(address))

    def put_object_sync(self, key: str, body: bytes) -> None:
        address = self._key(key)
        if not isinstance(body, bytes) or len(body) > self.transport.config.max_object_bytes:
            raise FoundationError(ErrorCode.INVALID_ARGUMENT, "invalid immutable object bytes")
        uncertain = False
        try:
            self._call(lambda: self.transport.put_object_sync(address, body))
        except FoundationError as exc:
            if exc.code != ErrorCode.DEPENDENCY_UNAVAILABLE:
                raise
            uncertain = True
        try:
            stored = self._call(lambda: self.transport.get_object_sync(address))
        except FoundationError as exc:
            if exc.code != ErrorCode.DEPENDENCY_UNAVAILABLE:
                raise
            raise FoundationError(
                ErrorCode.COMMIT_UNCONFIRMED, "object write awaits original-key readback"
            ) from None
        if stored == body:
            return
        if stored is not None:
            raise FoundationError(
                ErrorCode.IDEMPOTENCY_CONFLICT, "immutable object contains different bytes"
            )
        raise FoundationError(
            ErrorCode.COMMIT_UNCONFIRMED,
            "object write response lost; original key unconfirmed"
            if uncertain
            else "object write did not produce readable bytes",
        )

    def delete_object_sync(self, key: str) -> None:
        address = self._key(key)
        self._call(lambda: self.transport.delete_object_sync(address))

    def read_range_sync(self, key: str, start: int, end: int) -> bytes:
        address = self._key(key)
        if (
            type(start) is not int
            or type(end) is not int
            or start < 0
            or end < start
            or end - start > self.transport.config.max_range_bytes
        ):
            raise FoundationError(ErrorCode.INVALID_ARGUMENT, "invalid object byte range")
        return self._call(lambda: self.transport.read_range_sync(address, start, end))

    async def get_object(self, key: str) -> bytes | None:
        return await asyncio.to_thread(self.get_object_sync, key)

    async def put_object(self, key: str, body: bytes) -> None:
        await asyncio.to_thread(self.put_object_sync, key, body)

    async def delete_object(self, key: str) -> None:
        await asyncio.to_thread(self.delete_object_sync, key)

    async def read_range(self, key: str, start: int, end: int) -> bytes:
        return await asyncio.to_thread(self.read_range_sync, key, start, end)

    def close(self) -> None:
        self.transport.close()

    async def aclose(self) -> None:
        await asyncio.to_thread(self.close)
