'use strict';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const C=PlatformContent,M=PlatformModel,KEY='aether-platform-v3';
const labels={saved:'已保存',ready:'长期就绪',source_ready:'已形成长期事件',pending:'待处理',queued:'待领取',running:'执行中',waiting:'等待条件',completed:'已完成',succeeded:'已生效',complete:'完整可用',empty:'正常为空',degraded:'降级可用',unavailable:'不可用',denied:'拒绝',blocked:'已阻断',conflict:'版本冲突',processing_failed:'加工失败',failed:'失败',unknown:'结果未知',active:'有效',archived:'已归档',deleted:'已删除',superseded:'已替代',expired:'已到期',healthy:'可用',configured:'配置已更新',observing:'观察中',recovering:'处置中',verifying:'待业务复验',resolved:'已恢复',attention_required:'待人工处理',handoff_pending:'待引用交接',confirmed:'已确认',deferred:'暂缓',stale:'已失效',not_formed:'未形成事实',processing:'处理中',invalid:'已失效',removed:'已清理'};
const badge=s=>`<span class="tag ${['complete','ready','completed','succeeded','healthy','active','resolved','confirmed','configured'].includes(s)?'green':['denied','blocked','failed','unavailable','processing_failed','deleted'].includes(s)?'red':['degraded','waiting','unknown','attention_required','handoff_pending','expired'].includes(s)?'amber':'blue'}">${esc(labels[s]||s)}</span>`;
const icons={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7H14z',memories:'M4 5h16v14H4z M4 9h16 M8 5v14',recall:'M10 17a7 7 7 1 1 0-14 7 7 0 0 1 0 14z M15 15l6 6',requests:'M5 3h14v18H5z M8 7h8 M8 11h8 M8 15h5',tasks:'M4 5h16v15H4z M8 3v4 M16 3v4 M7 12l3 3 6-6',operations:'M3 7h16l-4-4 M21 17H5l4 4 M19 7v5 M5 17v-5',health:'M2 12h5l3-8 4 16 3-8h5',tenants:'M4 21V5l8-3v19 M12 8h8v13 M7 7v2 M7 12v2 M16 11v2 M16 16v2',configuration:'M12 4v16 M4 8h16 M4 16h16 M8 5v6 M16 13v6',traces:'M5 3v15h15 M5 7h8 M5 12h13 M13 5v4 M18 10v4',scenarios:'M4 4h16v16H4z M10 8l6 4-6 4z',coverage:'M6 7l2 2 4-5 M14 7h6 M6 16l2 2 4-5 M14 16h6',integration:'M8 7l-5 5 5 5 M16 7l5 5-5 5 M14 3l-4 18'};
const icon=k=>`<svg class="nav-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[k]||icons.overview}" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
const navs={business:[['工作空间',[['overview','工作台'],['memories','记忆与来源'],['recall','召回体验'],['requests','请求与结果']]]],ops:[['运行与诊断',[['health','健康与异常'],['tasks','后台任务'],['operations','自动调度'],['traces','日志与追踪']]],['受控维护观察',[['tenants','身份与授权'],['configuration','配置与备份']]]],review:[['产品行为验证',[['scenarios','完整场景演示'],['coverage','需求与流程覆盖'],['integration','接入与验收边界']]]]};
const titles=Object.fromEntries(Object.values(navs).flatMap(g=>g.flatMap(x=>x[1])));
let workspace,model,sceneStates={},sceneId=null,cursor=0,sceneContext={},page='overview',perspective='business',memoryFilter='',kindFilter='all',coverageTab='requirements',lastRecall=null;
function seedWorkspace(){const m=new M();m.remember('项目预算上限20万元，所有采购必须保留审批记录。每周五汇报进度，不得省略风险说明。',{source:'发布会议纪要 · 09/22'});m.process();m.remember('项目发布日期为10月15日，预发布环境在10月8日前完成验证。',{source:'发布计划 v1',kind:'episodic'});m.process();m.remember('当前任务：准备发布评审，重点核对预算、里程碑与风险。',{source:'项目 Agent · 当前任务'});m.select('b1');m.remember('公司 B 的内部采购计划。',{source:'B 内部样例'});m.select('a1');m.lastMemory=m.memories.find(x=>x.owner==='a1'&&x.kind==='working').id;m.lastTask=m.tasks.find(t=>t.memory_id===m.lastMemory).id;m.probe();return m;}
try{const saved=JSON.parse(sessionStorage.getItem(KEY)||'null');workspace=saved?new M(saved.workspace):seedWorkspace();sceneStates=saved?.scenes||{};}catch{workspace=seedWorkspace();}
model=workspace;
function save(){if(sceneId)sceneStates[sceneId]={state:model.state(),cursor,context:sceneContext};else workspace=model;try{sessionStorage.setItem(KEY,JSON.stringify({workspace:workspace.state(),scenes:sceneStates}));}catch{toast('会话存储不可用，当前页面仍可演示；刷新将重置。');}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3400);}
function go(view){location.hash='view='+view+(sceneId?'&scenario='+sceneId:'');}
function enterScene(id,reset=false){save();const s=C.scenes.find(s=>s.id===id);if(!s)return;sceneId=id;const old=!reset&&sceneStates[id];model=old?new M(old.state):new M();cursor=old?.cursor||0;sceneContext=old?.context||{};if(!old)s.setup(model);lastRecall=null;save();location.hash='view=scenarios&scenario='+id;render();}
function leaveScene(){save();sceneId=null;model=workspace;cursor=0;sceneContext={};lastRecall=null;location.hash='view=overview';render();}
function context(){return model.context();}
function visibleMemories(includeHistory=false){const c=context();return model.memories.filter(m=>includeHistory?c.status===undefined&&m.tenant===c.tenant&&(m.owner===c.actor||model.permits(c,m)):model.permits(c,m));}
function b(text,action,extra='',cls=''){return `<button class="${cls}" data-action="${action}" ${extra}>${text}</button>`;}
function empty(text='暂无记录',sub='完成相应操作后，记录会显示在这里。'){return `<div class="empty"><span>◇</span><strong>${text}</strong><p>${sub}</p></div>`;}
function head(title,sub,actions=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`;}
function card(title,body,action=''){return `<section class="card"><div class="card-head"><h2>${title}</h2>${action}</div><div class="card-body">${body}</div></section>`;}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function stat(name,value,note){return `<div class="stat"><div class="stat-label">${name}<span>↗</span></div><div class="stat-value">${value}</div><small>${note}</small></div>`;}
function kv(data){return `<dl class="kv">${Object.entries(data).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`;}
function raw(data){return `<details><summary>查看模拟对象与字段</summary><pre>${esc(JSON.stringify(data,null,2))}</pre></details>`;}
function renderResult(r){if(!r)return empty('等待一次操作','提交请求或推进场景，查看真实的模拟状态变化。');return `<div class="result"><div class="result-heading">${badge(r.status)}<strong>${esc(r.message||'操作结果')}</strong></div>${r.code?`<p>${esc(r.code)}</p>`:''}${r.selected?`<div class="chips">${r.selected.map(s=>`<span class="tag">${s==='working'?'当前记忆':'长期记忆'}</span>`).join('')}<span class="tag">${r.used??0} / ${r.budget??'—'} 模拟字符</span></div>`:''}${(r.missing||[]).map(s=>`<p>缺失说明：${esc(s)}</p>`).join('')}${(r.items||[]).map(i=>`<div class="result-item"><div class="chips"><span class="tag">${esc(i.representation||'原文')}</span>${i.conflict?'<span class="tag amber">有效冲突 · 需整组理解</span>':''}</div><blockquote>${esc(i.text)}</blockquote><small>${esc(i.source)} · v${i.version} · ${esc(i.memory_id)}</small></div>`).join('')}${r.artifact?`<div class="content-block">${esc(r.artifact.text)}</div><small>加工产物 · 质量与来源核验的模拟结果</small>`:''}${r.trace_id?`<div class="space-top">${b('查看处理链路 →','trace',`data-id="${esc(r.trace_id)}"`,'text-button')}</div>`:''}${raw(r)}</div>`;}
function memoryTable(items){return items.length?table(['记忆 / 来源','类型','当前状态','长期资格','操作'],items.map(m=>[`${b(esc(m.text.slice(0,32))+(m.text.length>32?'…':''),'memory',`data-id="${esc(m.id)}" data-version="${m.version}"`,'text-button')}<small>${esc(m.source)} · v${m.version}</small>`,{working:'当前任务',episodic:'历史事件',semantic:'稳定事实'}[m.kind]||esc(m.kind),badge(m.expiresAt<=model.now?'expired':m.state),badge(m.projection),b('详情','memory',`data-id="${esc(m.id)}" data-version="${m.version}"`,'text-button')])):empty('当前范围没有记忆','切换演示身份不会扩大权限。可在当前授权范围保存一条新记忆。');}
function overview(){const ms=visibleMemories(),ts=model.tasks.filter(t=>t.actor===model.actor&&t.tenant===model.requestTenant);return head('记忆服务工作台','连接当前任务与长期知识，让每次取用都有来源可查。',b('＋ 保存记忆','new-memory','','primary'))+`<div class="hero"><div><h2>从一条记忆，开始连续工作</h2><p>即时保存当前信息，后台形成可检索记忆，按需交付可信上下文。</p><div class="actions">${b('体验召回 →','navigate','data-view="recall"','primary')}${b('查看完整业务场景','scene','data-id="S01"')}</div></div><div class="pipeline">${[['01','保存与加工','内容、来源与版本一起保留'],['02','检索与组包','按记忆聚合，交付完整内容'],['03','自动调度','事件与周期驱动，核验后生效']].map(x=>`<div class="pipe-step"><span class="num">${x[0]}</span><strong>${x[1]}</strong><p>${x[2]}</p></div>`).join('')}</div></div><div class="stats">${stat('当前范围记忆',ms.length,'来自当前授权的模拟记录')}${stat('长期就绪',ms.filter(m=>m.projection==='ready').length,'完整索引核验后可参与召回')}${stat('后台待办',ts.filter(t=>t.status!=='completed').length,'保存成功与加工完成分别记录')}${stat('我的召回结果',model.contexts.filter(r=>r.actor===model.actor&&r.tenant===model.requestTenant).length,'历史结果重新获取仍需核验')}</div><div class="grid2">${card('最近记忆',memoryTable(ms.slice(-4)),b('查看全部','navigate','data-view="memories"','text-button'))}${card('处理流程',`<div class="flow-lanes">${[['Remember',['保存','加工','Ready']],['Recall',['候选','正文','Context']],['Operate',['决策','执行','对账']]].map(([name,steps])=>`<div class="flow-lane"><strong>${name}</strong><div class="chips">${steps.map(s=>`<span>${s}</span>`).join('<em>›</em>')}</div></div>`).join('')}</div><div class="space-top notice">Operate 由系统自动运行。这里的按钮推进模拟时间与场景，不是新增调度业务接口。</div>${b('观察运行状态 →','navigate','data-view="health"','text-button')}`)}</div>${card('近期处理记录',ts.length?ts.slice(-4).reverse().map(t=>`<div class="activity-row"><div class="symbol">${icon('tasks')}</div><div class="grow"><strong>${t.kind==='maintenance'?'维护任务':'记忆加工任务'}</strong><p>${esc(t.id)} · 原主体 ${esc(t.actor)} · ${t.attempts} 次尝试</p></div>${badge(t.status)}${b('查看','task',`data-id="${t.id}"`,'text-button')}</div>`).join(''):empty())}`;}
function memories(){let items=visibleMemories(true).filter(m=>(kindFilter==='all'||m.kind===kindFilter)&&(!memoryFilter||[m.text,m.id,m.source].join(' ').toLowerCase().includes(memoryFilter.toLowerCase())));return head('记忆与来源','查看原文、长期事件、稳定事实及其版本关系。',b('＋ 保存记忆','new-memory','','primary'))+`<div class="toolbar"><input id="memory-search" aria-label="搜索记忆" placeholder="搜索正文、来源或记忆编号" value="${esc(memoryFilter)}"><select id="kind-filter" aria-label="记忆类型">${[['all','全部类型'],['working','当前任务'],['episodic','历史事件'],['semantic','稳定事实']].map(([v,t])=>`<option value="${v}" ${kindFilter===v?'selected':''}>${t}</option>`).join('')}</select></div><div class="card">${memoryTable(items)}</div><p class="counter-note space-top">${items.length} 条模拟记录 · 更正、归档、到期与删除保留不同状态</p>`;}
function planView(plan){if(!plan)return empty('尚未形成候选计划','提交一次召回后，查看块、记忆与组包之间的关系。');return `<p>${esc(plan.reason)}</p><div class="mini-metrics"><div class="mini-metric"><b>${plan.hits.length}</b><small>块命中</small></div><div class="mini-metric"><b>${plan.mainCandidates.length} / ${plan.topK}</b><small>长期记忆候选</small></div><div class="mini-metric"><b>${plan.batches}</b><small>取块批次</small></div></div><div class="notice">${esc(plan.space)} · 同一记忆多个块只占一个名额。Working 和关系补全成员不挤占主候选 K，全部计入正文预算。</div>${table(['块','记忆','相似度（模拟）'],plan.hits.slice(0,8).map(h=>[esc(h.id),esc(h.memory_id),h.score]))}<div class="space-top">${plan.groups.map(g=>`<div class="activity-row"><div class="grow"><strong>${g.conflict?'完整冲突组':'完整记忆'}</strong><p>${esc(g.members.join(' · '))}</p></div><span class="tag">${g.members.length} 条</span></div>`).join('')}</div>${plan.excluded.map(e=>`<p class="small">${esc(e.group)}：${esc(e.reason)}</p>`).join('')}`;}
function recall(){return head('召回体验','应用调用与 Agent 工具使用同一条处理链路。')+`<div class="grid2 grid-even">${card('发起召回',`<form id="recall-form" class="form-stack"><label>查询问题<textarea name="query" rows="3" placeholder="例如：项目预算和发布要求是什么？">${esc(lastRecall?.query||'项目预算')}</textarea></label><div class="form-grid"><label>记忆来源<select name="sources"><option value="auto">自动选择</option><option value="working">仅当前任务</option><option value="long_term">仅长期记忆</option><option value="both">当前 + 长期</option></select></label><label>调用方式<select name="caller"><option>应用直接调用</option><option>Agent 工具调用</option></select></label><label>主候选记忆数 K<input name="topK" type="number" min="1" max="20" value="3" required></label><label>预算 · 模拟字符<input name="budget" type="number" min="1" max="10000" value="600" required></label><label>正文表示<select name="representation"><option value="original">原文</option><option value="compressed">允许合格压缩表示</option></select></label><label>当前任务范围<select name="session"><option value="launch">发布任务</option><option value="other">其他任务</option></select></label></div><label><span><input name="pause" type="checkbox" style="width:auto"> 在最终交付前暂停，用于验证撤权与版本变化</span></label><div class="actions"><button class="primary" type="submit">检索并组装上下文</button>${model.draft?b('继续最终交付','finish'):''}</div><small>检索与排序为确定性模拟；预算含正文、来源及冲突说明，正式系统采用目标 tokenizer。</small></form>`)}${card('调用方结果',renderResult(lastRecall?.result||model.last?.context_id&&model.last))}</div>${card('候选与正文组包',planView(model.lastPlan),b('演示多块命中','scene','data-id="S13"','text-button'))}`;}
function requests(){const c=context(),rows=c.status?[]:model.contexts.filter(r=>r.actor===c.actor&&r.tenant===c.tenant);return head('请求与结果','查看原结果；重新获取仍按当前权限、版本和生命周期核验。')+`<div class="card">${rows.length?table(['结果编号','来源','结果','条目','操作'],rows.slice().reverse().map(r=>[esc(r.id),esc(r.selected.join(' / ')),badge(r.status),r.items.length,b('重新获取','replay',`data-id="${r.id}"`,'text-button')])):empty('暂无召回结果')}</div>${renderResult(model.last)}`;}
function taskView(){const ts=model.tasks;return head('后台任务','受控运行观察 · 任务保存原主体，领取任务后由对应业务处理器执行。',b('推进虚拟时间 +40s','advance'))+`<div class="notice">${sceneId?'当前专题':'共享工作区'}中的模拟任务。RF 负责领取、租约、事务和恢复机制；B/A/C 处理器负责业务判断。</div><div class="card">${ts.length?table(['任务','所属范围','状态','尝试 / 租约','操作'],ts.map(t=>[`${esc(t.id)}<small>${esc(t.kind)} · ${esc(t.memory_id)}</small>`,`${esc(t.tenant)} / ${esc(t.actor)}`,badge(t.status),`${t.attempts} 次 / ${t.lease>model.now?'有效':'无有效租约'}`,b('详情','task',`data-id="${t.id}"`,'text-button')])):empty()}</div><div class="actions space-top">${b('检测任务与依赖','probe')}${b('恢复判定','recover')}${b('演示 Worker 中断','scene','data-id="S11"')}${b('观察监测处置','scene','data-id="S16"')}</div>${renderResult(model.last)}`;}
function operations(){return head('自动调度','受控运行观察 · 事件或周期评估触发，目标生效与旧副本清理分别记录。',b('演示迁移交接','scene','data-id="S18"','primary'))+`<div class="stats">${stat('累计动作',model.actions.length,'来自当前模拟的决策')}${stat('已核验生效',model.actions.filter(a=>a.status==='succeeded').length,'目标可读且引用已确认')}${stat('结果未知',model.actions.filter(a=>a.status==='unknown').length,'继续查询原动作')}${stat('清理待办',model.actions.filter(a=>a.cleanup==='pending').length,'不与目标生效混淆')}</div><div class="card">${model.actions.length?table(['动作 / 对象','迁移','执行结果','引用交接','旧副本','操作'],model.actions.map(a=>[`${esc(a.id)}<small>${esc(a.memory_id)}</small>`,`${esc(a.from)} → ${esc(a.to)}`,badge(a.status),badge(a.handoff||'pending'),badge(a.cleanup||'pending'),b('详情','action-detail',`data-id="${a.id}"`,'text-button')])):empty('尚未产生调度动作','访问、存储变化或周期评估满足规则后自动触发。')}</div><div class="actions space-top">${b('推进周期评估','periodic')}${b('查询原动作','reconcile')}${b('升降层与 Unknown 场景','scene','data-id="S06"')}</div>${renderResult(model.last)}`;}
const healthNames={api:'业务入口',worker:'后台执行',model:'提取模型',vector:'长期检索',object:'正文读取',executor:'迁移执行',identity:'身份验证'};
function health(){return head('健康与异常','先确认能力，再恢复任务；维护完成后，独立业务复验决定是否关闭异常。',b('执行健康检测','probe','','primary'))+`<div class="notice">健康证据：${esc(model.readiness())}。开关用于模拟依赖变化，不代表真实服务操作。</div><div class="health-grid">${Object.entries(model.health).map(([k,v])=>`<div class="health-card">${badge(v?'healthy':'unavailable')}<strong>${healthNames[k]}</strong><small>${v?'模拟依赖可以响应':'模拟依赖当前失效'}</small><br>${b(v?'模拟故障':'模拟依赖恢复','health-toggle',`data-id="${k}"`)}</div>`).join('')}</div>${card('异常处置',model.incidents.length?table(['异常 / 原操作','状态','维护任务','业务复验','操作'],model.incidents.map(i=>[`${esc(i.id)}<small>${esc(i.operation_id)}</small>`,badge(i.state),esc(i.task_id),badge(i.verification),b('查看','incident',`data-id="${i.id}"`,'text-button')])):empty('暂无已触发的异常','连续异常达到演示阈值后，维护任务进入公共队列。'))}<div class="actions space-top">${b('采样一次故障信号','sample')}${b('执行已登记维护','maintain')}${b('独立业务复验','verify')}${b('模拟业务验证通过','business-pass')}${b('推进时间 +40s','advance')}${b('完整处置演示','scene','data-id="S16"')}</div>${renderResult(model.last)}`;}
function tenants(){return head('身份与授权','受控配置观察 · 演示既有身份映射和业务授权，不扩展成员管理或产品角色体系。',b('完整授权场景','scene','data-id="S09"','primary'))+`<div class="grid2 grid-even">${card('业务租户',table(['租户','稳定编号','状态','配置版本'],Object.entries(model.tenants).map(([id,t])=>[esc(t.name),id,badge(t.enabled?'active':'blocked'),t.revision])))}${card('身份映射',table(['模拟主体','归属','状态'],Object.entries(model.actors).map(([id,a])=>[esc(id),esc(a.tenant||'尚未绑定'),badge(a.enabled?'active':'blocked')])))}</div>${card('明确的资源许可',model.grants.length?table(['资源','被授权主体','允许操作','状态'],model.grants.map(g=>[esc(g.memory),esc(g.actor),esc(g.operations.join(' / ')),badge(g.active&&g.expires>model.now?'active':'blocked')])):empty('尚未授予共享','同租户主体默认不能读取他人的私有记忆。'))}<div class="actions space-top">${[['grant','授予 A2 目标只读'],['revoke','撤销共享'],['disable','停用 A'],['enable','启用 A'],['invalid','模拟配置失败'],['external_revoke','模拟外部撤权']].map(([a,t])=>b(t,'config-op',`data-id="${a}"`)).join('')}</div><p class="small space-top">目标：${esc(model.lastMemory||'无')} · 演示外部撤权窗口为 30 秒，不是正式 SLA。</p>${renderResult(model.last)}`;}
function configuration(){return head('配置与备份','受控维护观察 · 配置快照与部署变更分开，隔离恢复不覆盖在线数据。')+`<div class="grid2 grid-even">${card('当前配置',kv({'配置版本':model.configVersion,'策略版本':model.configuration.strategy,'后台上限':model.configuration.maxBackground,'健康证据':model.readiness()})+`<form id="configuration-form" class="form-stack"><div class="form-grid"><label>预期当前版本<input type="number" name="expected" value="${model.configVersion}" required min="1"></label><label>后台任务上限<input type="number" name="maxBackground" value="${model.configuration.maxBackground}" min="1" required></label></div><button class="primary">条件更新配置快照</button></form>`)}${card('备份与隔离恢复',`<div class="notice">本轮 RF 备份范围：SQLite 中的业务与任务记录。外部向量库、模型、独立日志库需单独方案。此页面只模拟清单与隔离核验。</div><div class="actions">${b('创建模拟备份','backup-isolated')}${b('隔离恢复演练','restore-isolated')}</div>${model.savedBackups.length?table(['备份','配置','状态'],model.savedBackups.map(x=>[esc(x.id),x.version,badge(x.state)])):empty('暂无备份清单')}${model.isolatedRestore?`<p class="small space-top">${esc(model.isolatedRestore.id)} · 当前授权核验 · 未覆盖在线数据</p>`:''}`)}</div>${card('配置历史',model.configHistory.length?table(['历史版本','策略','后台上限'],model.configHistory.map(x=>[x.version,esc(x.value.strategy),x.value.maxBackground])):empty('尚无配置变更'))}${renderResult(model.last)}`;}
function traces(){const rows=model.spans;return head('日志与追踪','受控诊断观察 · 正文默认不出现在列表，按原业务链路追查状态与原因。',b('导出模拟记录','export'))+`<div class="toolbar"><input id="trace-search" aria-label="查找追踪" placeholder="搜索 trace、任务编号、模块或错误原因"></div><div id="trace-table" class="card">${traceTable(rows)}</div>`;}
function traceTable(rows){return rows.length?table(['Trace / 节点','模块','阶段','状态','操作'],rows.slice().reverse().slice(0,120).map(s=>[`${esc(s.trace_id)}<small>${esc(s.span_id)} · 虚拟 ${s.time}s</small>`,esc(s.owner),`${esc(s.stage)}<small>${esc(s.reason)}</small>`,badge(s.status),b('链路','trace',`data-id="${s.trace_id}"`,'text-button')])):empty();}
function scenarios(){const s=sceneId&&C.scenes.find(x=>x.id===sceneId),next=s?.steps[cursor];return head('完整场景演示','逐步查看输入、状态、结果与负责模块。专题独立预置，切换页面保留当前专题状态。',sceneId?b('返回共享工作区','leave-scene'):b('开始完整主线','scene','data-id="S01"','primary'))+(s?`<section class="scene-controls"><div style="flex:1"><small>${s.id} · ${s.title} · ${cursor}/${s.steps.length}</small><h2>${next?esc(next.title):'本专题已完成'}</h2><p>${next?esc(next.explain):'可以回看结果与记录，或选择另一专题。'}</p><div class="progress-track"><i style="width:${cursor/s.steps.length*100}%"></i></div></div><div class="actions">${b('重置本专题','reset-scene')}${b(next?'执行下一步 →':'已完成','next',next?'':'disabled','primary')}</div></section><div class="scene-layout">${card('本步结果',renderResult(model.last))}${card('场景步骤',`<div class="step-list">${s.steps.map((st,i)=>`<div class="step-row ${i<cursor?'done':i===cursor?'current':''}"><b class="badge-num">${i<cursor?'✓':i+1}</b><div>${esc(st.title)}<br><span>${i<cursor?'已执行':i===cursor?'下一步':'待执行'}</span></div></div>`).join('')}</div>`)}</div><div class="actions space-top">${b('查看当前记忆','navigate','data-view="memories"')}${b('查看候选与组包','navigate','data-view="recall"')}${b('查看运行与异常','navigate','data-view="health"')}${b('查看追踪','navigate','data-view="traces"')}</div><h2 class="space-top" style="margin-bottom:14px">选择其他专题</h2>`:'')+`<div class="scene-grid">${C.scenes.map(s=>`<button class="scene-card ${sceneId===s.id?'active':''}" data-action="scene" data-id="${s.id}"><div class="chips"><span class="tag blue">${s.id}</span><span class="tag">${s.phase}</span></div><strong>${s.title}</strong><p>${s.sub}</p><small>${s.steps.length} 步 · ${s.fr.join(' / ')}${sceneStates[s.id]?' · 已执行 '+sceneStates[s.id].cursor+' 步':''}</small></button>`).join('')}</div>`;}
function coverage(){return head('需求与流程覆盖','覆盖表示已提供目标行为场景；不等于后端功能、性能或生产验收通过。',b('查看接入边界','navigate','data-view="integration"'))+`<div class="stats">${stat('功能需求',C.requirements.length,'FR01–FR18 均有对应场景')}${stat('可操作专题',C.scenes.length,'包括后续 P1 预测场景')}${stat('流程分组',C.flowCoverage.length,'RF / Remember / Recall / Operate')}${stat('真实验收','待执行','模型、性能与长稳不能由 Mock 证明')}</div><div class="tabs">${[['requirements','功能需求'],['flows','流程架构'],['nonfunctional','非功能与交付']].map(([v,t])=>b(t,'coverage-tab',`data-id="${v}"`,coverageTab===v?'active':'')).join('')}</div><div class="card">${coverageTab==='requirements'?table(['需求','目标行为','场景入口','阶段 / 状态'],C.requirements.map(r=>[`${r.id}<small>PRD ${r.section}</small>`,r.name,`<div class="chips">${r.scenes.map(id=>b(id,'scene',`data-id="${id}"`,'text-button')).join('')}</div>`,`${r.phase}<small>目标行为模拟</small>`])):coverageTab==='flows'?table(['图中位置','关键过程','场景'],C.flowCoverage.map(([id,title,ss])=>[id,title,ss.map(s=>b(s,'scene',`data-id="${s}"`,'text-button')).join(' ')])):table(['PRD','要求','目标/边界','验证状态'],C.nonfunctional.map(([sec,n,t,limit])=>[sec,n,`${t}<small>${limit}</small>`,badge('待真实验收')]))}</div><div class="notice space-top">流程存在历史歧义时，本 Mock 按 PRD 处理：保留其他独立可信内容的降级路径；不完整组排除后继续；恢复按当前权限及有效配置核验。完整图源的历史文字不覆盖这些产品规则。</div><div class="link-row"><a href="../PRD版本/AetherBrain_P3_PRD_租户补全版_V1.3.docx">PRD V1.3 ↗</a><a href="../架构设计/P3全景流程_Excalidraw/P3_整体架构与完整流程.excalidraw">完整流程图源 ↗</a><a href="Mock需求与流程覆盖_20260922.md">覆盖与边界说明 ↗</a></div>`;}
function integration(){return head('接入与验收边界','同一套记忆服务，支持应用直接调用与 Agent 工具调用。')+`<div class="grid2 grid-even">${card('两个对外功能',`<div class="activity-row"><div class="symbol">B</div><div class="grow"><strong>Remember · 保存及生命周期</strong><p>保存、处理查询、更正、归档、到期、删除</p></div></div><div class="activity-row"><div class="symbol">A</div><div class="grow"><strong>Recall · 记忆取用</strong><p>来源选择、授权核验、完整上下文、原结果查询</p></div></div><div class="notice space-top">应用与 Agent 工具遵守同一输入、授权与结果规则；调用者不用另发调度请求或提供模型采用回执。</div>`)}${card('内部自动闭环',`<div class="flow-lanes"><div class="flow-lane"><strong>RF</strong><p>身份、事务、任务、事件、日志与恢复</p></div><div class="flow-lane"><strong>Operate</strong><p>内容/访问变化与周期评估 → 决策 → 执行 → 核验</p></div><div class="flow-lane"><strong>提供方</strong><p>正文、索引与实际存储操作的可验证结果</p></div></div>`)}</div>${card('这份原型的范围',`<p>参考文件只用于导航、工作台、列表和详情交互设计。页面是产品评审与接口行为观察工具，不把登录、成员邀请、计费或人工审批迁移加入 PRD 范围。</p><div class="space-top">${table(['内容','本原型如何处理'],[['业务状态与异常','可操作的本地状态模拟，页面共用数据'],['编码、模型、压缩和向量检索','预设/确定性模拟；不制造真实质量或性能数据'],['预算','按实际呈现文本的字符数模拟；正式系统按目标 tokenizer'],['外部身份与 P2','展示授权、传播、地址及结果规则；不声称真实接入'],['备份与恢复','RF 范围和隔离恢复模拟；旧权限与有效性屏障独立保留是设计假设'],['运行指标、长稳和发布','列出 PRD 目标与真实验收要求，当前不填写达标值']])}</div>`)}<div class="link-row"><a href="../../AgentJYS-main/docs/p3/development/08_RF运行服务与HTTP接入.md">当前真实 HTTP 接入说明 ↗</a><a href="../开发协作/11_RF公共底座实现与接入_20260922.md">实际实现范围 ↗</a><a href="../测试与验收/测试人员交接包_20260922/00_先读我_测试交接说明.md">测试交接包 ↗</a></div>`;}
const pages={overview,memories,recall,requests,tasks:taskView,operations,health,tenants,configuration,traces,scenarios,coverage,integration};
function render(){perspective=Object.keys(navs).find(k=>navs[k].some(g=>g[1].some(([id])=>id===page)))||'business';$('navigation').innerHTML=navs[perspective].map(([title,items])=>`<div class="nav-caption">${title}</div>${items.map(([id,t])=>`<button class="nav-link ${page===id?'active':''}" data-action="navigate" data-view="${id}" ${page===id?'aria-current="page"':''}>${icon(id)}${t}</button>`).join('')}`).join('');document.querySelectorAll('[data-perspective]').forEach(b=>b.classList.toggle('active',b.dataset.perspective===perspective));$('crumb').textContent=titles[page];$('dataset-label').textContent=sceneId?'专题 '+sceneId+' · 独立模拟数据':'共享工作区';$('identity').value=model.actor;$('main').innerHTML=pages[page]();if(page==='recall'&&lastRecall?.options){for(const [k,v] of Object.entries(lastRecall.options)){const field=$('recall-form').elements.namedItem(k);if(field){if(field.type==='checkbox')field.checked=!!v;else field.value=v;}}}document.title=titles[page]+' · Aether';}
function showDrawer(title,body,kicker='模拟记录详情'){$('drawer-title').textContent=title;$('drawer-kicker').textContent=kicker;$('drawer-body').innerHTML=body;if(!$('drawer').open)$('drawer').showModal();}
function showModal(title,body){$('modal-title').textContent=title;$('modal-body').innerHTML=body;if(!$('modal').open)$('modal').showModal();}
function memoryDetail(id,version){const m=model.memories.find(x=>x.id===id&&(!version||x.version===Number(version)));const c=context();if(!m||c.status||m.tenant!==c.tenant||m.owner!==c.actor&&!model.permits(c,m)){toast('当前身份无权查看这条记忆。');return;}model.lastMemory=id;model.lastTask=model.tasks.filter(t=>t.memory_id===id).at(-1)?.id;showDrawer('记忆详情',kv({'记忆编号':m.id,'版本 / 类型':'v'+m.version+' / '+({working:'当前任务',episodic:'历史事件',semantic:'稳定事实'}[m.kind]),'状态':labels[m.state],'来源':m.source,'所属范围':m.tenant+' / '+m.owner,'正文位置':m.bodyLocation||'尚未登记','长期关联':m.longterm_id||m.origin_id||'独立记忆'})+`<div class="content-block">${esc(m.text)}</div>${m.artifact?`<h3>合格加工表示</h3><div class="content-block">${esc(m.artifact.text)}</div>`:''}<div class="actions">${b('加工与索引核验','process',`data-id="${esc(model.lastTask||'')}"`)}${b('更正','edit-memory',`data-id="${id}"`)}${b(m.state==='archived'?'重新激活':'归档','mutate',`data-op="${m.state==='archived'?'reactivate':'archive'}" data-id="${id}"`)}${b('到期','expire',`data-id="${id}"`)}${b('删除','delete-memory',`data-id="${id}"`,'danger')}</div>${m.chunks?`<h3 class="space-top">块与发布批次</h3>${table(['块','版本 / 批次','核验'],m.chunks.map(c=>[esc(c.id),'v'+c.version+' / '+esc(c.batch),badge(c.verified?'ready':'pending')]))}`:''}${raw(m)}`);save();}
function taskDetail(id){const t=model.tasks.find(t=>t.id===id);if(!t)return;showDrawer('任务详情',kv({'任务编号':t.id,'处理器':t.kind,'原主体':t.actor+' / '+t.tenant,'状态':labels[t.status],'领取代次':t.fence,'尝试次数':t.attempts,'失败原因':t.error||'无','Trace':t.trace_id})+`<div class="actions">${b('推进此任务','process',`data-id="${t.id}"`)}${b('查询原任务','query-task',`data-id="${t.id}"`)}${b('查看追踪','trace',`data-id="${t.trace_id}"`)}</div>${raw(t)}`,'受控任务观察');}
function traceDetail(id){const rows=model.spans.filter(s=>s.trace_id===id);showDrawer('处理链路',`<p>${esc(id)} · ${rows.length} 个模拟节点</p><div class="space-top">${rows.map(s=>`<div class="trace-step"><strong>${esc(s.stage)}</strong>${badge(s.status)}<p>${esc(s.owner)} · 虚拟 ${s.time}s${s.reason?' · '+esc(s.reason):''}</p><details><summary>节点输入 / 输出（演示样例）</summary><pre>${esc(JSON.stringify({input:s.input,output:s.output},null,2))}</pre></details></div>`).join('')}</div>`,'受控诊断 · 正文仅为虚构样例');}
function newMemory(editId){const m=editId&&model.active(editId);showModal(m?'更正记忆':'保存新记忆',`<form id="memory-form" class="form-stack" data-edit="${esc(editId||'')}"><div class="form-grid"><label>类型<select name="kind" ${m?'disabled':''}><option value="working" ${m?.kind==='working'?'selected':''}>当前任务信息</option><option value="episodic" ${m?.kind==='episodic'?'selected':''}>事件 / 文档来源</option>${m?.kind==='semantic'?'<option value="semantic" selected>稳定事实</option>':''}</select></label><label>来源名称<input name="source" required ${m?'readonly':''} value="${esc(m?.source||'项目会议记录')}"></label><label class="full">内容<textarea name="text" rows="6" required placeholder="输入带有业务事实、条件和来源的内容">${esc(m?.text||'')}</textarea></label></div>${!m?'<label>可选：读取本地 TXT 样例<input id="sample-file" type="file" accept=".txt,text/plain"></label><small>文本只在浏览器读取；PDF/Word 解析在专题 S10 使用预设内容模拟。</small>':''}<div class="actions"><button class="primary" type="submit">${m?'提交更正':'保存并登记后台任务'}</button><button type="button" data-close>取消</button></div></form>`);}
function after(result){save();render();if(result?.message)toast(result.message);}
function command(action,id,button){const old=model.last;switch(action){
  case'navigate':go(button.dataset.view);document.querySelector('.sidebar').classList.remove('open');return;
  case'scene':enterScene(id);return;case'leave-scene':leaveScene();return;case'reset-scene':enterScene(sceneId,true);return;
  case'next':{const s=C.scenes.find(s=>s.id===sceneId);if(s&&cursor<s.steps.length){s.steps[cursor].act(model,sceneContext);cursor++;after(model.last);}return;}
  case'new-memory':newMemory();return;case'edit-memory':$('drawer').close();newMemory(id);return;case'memory':memoryDetail(id,button.dataset.version);return;case'task':taskDetail(id);return;case'trace':traceDetail(id);return;
  case'action-detail':{const a=model.actions.find(a=>a.id===id);if(!a)return;model.lastAction=id;showDrawer('调度动作',kv({'原动作':a.id,'目标':a.memory_id+' / v'+a.version,'迁移':a.from+' → '+a.to,'状态':labels[a.status],'正文交接':a.handoff||'尚未确认','旧副本清理':a.cleanup||'尚未进入','旧位置':a.oldLocation||'原位置仍保留','新位置':a.newLocation||'待核验'})+`<div class="actions">${b('确认引用交接','handoff',`data-id="${id}"`)}${b('清理旧副本','clean-old',`data-id="${id}"`)}${b('追踪','trace',`data-id="${a.trace_id}"`)}</div>${raw(a)}`);return;}
  case'incident':{const i=model.incidents.find(i=>i.id===id);if(i)showDrawer('异常处置',kv({'异常':i.id,'状态':labels[i.state],'原操作':i.operation_id,'维护任务':i.task_id,'业务复验':i.verification,'证明':i.proof||'尚未取得'})+raw(i));return;}
  case'process':model.process(id||model.lastTask);break;case'query-task':model.queryTask(id);break;case'finish':model.finishPending();lastRecall={...lastRecall,result:model.last};break;
  case'replay':model.replay(id);break;case'mutate':model.mutate(button.dataset.op,undefined,id);break;case'expire':model.expire(id);break;
  case'delete-memory':showModal('删除模拟记忆',`<p>立即阻断这条记忆及失效派生内容的后续使用。物理清理作为独立待办。</p><div class="actions space-top">${b('确认删除模拟数据','confirm-delete',`data-id="${esc(id)}"`,'danger')}<button data-close>取消</button></div>`);return;
  case'confirm-delete':model.mutate('delete',undefined,id);$('modal').close();$('drawer').close();break;
  case'advance':model.advance(40);break;case'probe':model.probe();break;case'recover':model.recover();break;case'reconcile':model.reconcile();break;
  case'periodic':model.schedule('down');break;case'handoff':model.handoff(id);break;case'clean-old':model.cleanOld(id);break;
  case'health-toggle':if(model.health[id]){model.health[id]=false;model.probe();}else model.restoreDependency(id);break;
  case'sample':model.sampleSignal();break;case'maintain':model.executeMaintenance();break;case'verify':model.verifyBusiness();break;case'business-pass':model.businessVerified=true;toast('已注入独立业务成功证据，仍需执行复验判断。');save();return;
  case'config-op':model.configure(id);break;case'backup-isolated':model.createBackup();break;case'restore-isolated':model.restoreIsolated();break;
  case'coverage-tab':coverageTab=id;render();return;
  case'export':{const payload={format:'aether-platform-review-v3',prd:'V1.3',mode:'simulated',scenario:sceneId,state:model.state(),notice:'仅为模拟记录，不是产品验收证据'};const u=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='aether-mock-'+(sceneId||'workspace')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);return;}
}if(model.last!==old){if($('drawer').open)$('drawer').close();after(model.last);}}
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.hasAttribute('data-close')){el.closest('dialog')?.close();return;}if(el.dataset.perspective){go(navs[el.dataset.perspective][0][1][0][0]);return;}if(el.dataset.action)command(el.dataset.action,el.dataset.id,el);});
document.addEventListener('submit',e=>{if(e.target.id==='recall-form'){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const options={...data,pause:data.pause==='on'};model.recall(options);lastRecall={query:data.query,options,result:model.last};after(model.last);}if(e.target.id==='memory-form'){e.preventDefault();const f=e.target,data=Object.fromEntries(new FormData(f));if(f.dataset.edit)model.mutate('correct',data.text,f.dataset.edit);else model.remember(data.text,{kind:data.kind,source:data.source});$('modal').close();after(model.last);}if(e.target.id==='configuration-form'){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));model.setConfiguration(Number(data.expected),{maxBackground:Number(data.maxBackground)});after(model.last);}});
document.addEventListener('input',e=>{if(e.target.id==='memory-search'){memoryFilter=e.target.value;const start=e.target.selectionStart;render();$('memory-search').focus();$('memory-search').setSelectionRange(start,start);}if(e.target.id==='trace-search'){const q=e.target.value.toLowerCase();$('trace-table').innerHTML=traceTable(model.spans.filter(s=>[s.trace_id,s.span_id,s.stage,s.owner,s.reason,JSON.stringify(s.input).replace(/"text":"[^"]*"/g,'')].join(' ').toLowerCase().includes(q)));}});
document.addEventListener('change',async e=>{if(e.target.id==='kind-filter'){kindFilter=e.target.value;render();}if(e.target.id==='sample-file'){const f=e.target.files[0];if(!f)return;if(f.size>1024*1024){toast('演示样例请使用 1 MB 以内的 TXT 文件。');return;}try{const text=await f.text();$('memory-form').elements.text.value=text;$('memory-form').elements.source.value=f.name;}catch{toast('样例读取失败，请直接粘贴文本。');}}});
$('identity').onchange=()=>{model.select($('identity').value);lastRecall=null;model.last=null;model.lastPlan=null;$('drawer').close();save();render();};
$('theme-toggle').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';};
$('menu-toggle').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
$('open-boundary').onclick=()=>showDrawer('范围与模拟说明',`<div class="notice">本原型用于 PRD 与流程评审。顶部视角切换只改变观察方式，不代表新增产品角色。</div>${kv({'需求基线':'PRD V1.3','行为范围':'FR01–FR18 与 RF/B/A/C 关键流程','运行方式':'本地浏览器状态、虚拟时钟和预设规则','真实服务':'未连接模型、身份平台、Milvus 或 P2','数据保持':'当前标签页会话内保存；专题与共享工作区独立','正式验收':'质量、性能、隔离与 24/72 小时长稳另行验证'})}<p>使用参考原型的工作台、导航、表格与详情交互；不增加成员邀请、收费或人工审核调度。</p>`);
function route(){const params=new URLSearchParams(location.hash.slice(1));const sid=params.get('scenario');if(sid&&sid!==sceneId){const s=C.scenes.find(s=>s.id===sid);if(s){save();lastRecall=null;sceneId=sid;const stored=sceneStates[sid];model=stored?new M(stored.state):new M();cursor=stored?.cursor||0;sceneContext=stored?.context||{};if(!stored)s.setup(model);}}else if(!sid&&sceneId){save();lastRecall=null;sceneId=null;model=workspace;}page=params.get('view')||(sid?'scenarios':'overview');if(!pages[page])page='overview';render();window.scrollTo({top:0,behavior:'instant'});}
window.addEventListener('hashchange',route);route();
