'use strict';
const $=id=>document.getElementById(id),escapeHTML=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const {scenes,decisions}=P3ReviewContent;
const labels={saved:'已保存',ready:'长期就绪',complete:'完整可用',degraded:'降级可用',empty:'正常空',unavailable:'不可用',denied:'拒绝访问',blocked:'已阻断',waiting:'等待推进',unknown:'结果未知 · 待核对',completed:'已完成 · 模拟',configured:'配置已更新',healthy:'探测正常',processing_failed:'加工失败',failed:'明确失败',conflict:'幂等冲突',active:'当前有效',archived:'已归档',superseded:'已替代',deleted:'已删除',pending:'待处理',queued:'待领取',running:'处理中',expired:'租约过期',succeeded:'执行已确认',stale:'旧结果已隔离',submitted:'已受理',deferred:'暂缓',passed:'核验通过',acked:'已确认',removed:'已清理'};
const tiers={hot:'热',warm:'温',cold:'冷'};
const names={api:'API进程',worker:'后台Worker',model:'提取模型',vector:'向量服务',object:'正文服务',executor:'执行端',identity:'身份验证'};
const key='aether-p3-mock-v13-20260920-r2';let sessions={},currentId='S01',model,context={},cursor=0,view='story',selectedTrace='all',storageOK=true;
try{const saved=JSON.parse(sessionStorage.getItem(key)||'{}');sessions=saved.sessions||{};}catch{storageOK=false;}
function label(s){return ({invalid:'资格失效',none:'无待办'})[s]||labels[s]||s;}
function color(s){return ['denied','blocked','failed','unavailable','conflict'].includes(s)?'bad':['degraded','processing_failed','unknown','deferred','expired','waiting'].includes(s)?'warn':['saved','ready','complete','completed','healthy','passed','succeeded','configured'].includes(s)?'good':'neutral';}
function badge(s){return `<span class="badge ${color(s)}">${escapeHTML(label(s))}</span>`;}
function traceButton(id){return `<button class="trace-link" data-trace="${escapeHTML(id)}">${escapeHTML(id)} ↗</button>`;}
function save(){sessions[currentId]={state:model.state(),context,cursor};try{sessionStorage.setItem(key,JSON.stringify({sessions}));}catch{storageOK=false;} }
function scene(){return scenes.find(s=>s.id===currentId);}
function load(id,reset=false){if(model)save();currentId=scenes.some(s=>s.id===id)?id:'S01';const existing=reset?null:sessions[currentId];if(existing){model=new P3ReviewModel(existing.state);context=existing.context;cursor=existing.cursor;}else{model=new P3ReviewModel();context={};cursor=0;scene().setup(model);model.last=null;}selectedTrace='all';view='story';save();render();}
function resultHTML(r){
  if(!r)return '<div class="empty"><span class="symbol">↗</span><strong>从上方第一步开始</strong><p>每一步改变同一份模拟状态。<br>先看调用结果，再展开内部证据。</p></div>';
  let html=`<h3 class="result-title">${escapeHTML(label(r.status))}</h3><p class="result-message">${escapeHTML(r.message||'当前模拟处理结果。')}</p><div class="result-meta">${traceButton(r.trace_id)}${[r.memory_id,r.task_id,r.context_id,r.code].filter(Boolean).map(x=>`<span class="badge">${escapeHTML(x)}</span>`).join('')}</div>`;
  if(r.saved!==undefined)html+=`<div class="result-stat"><div><span>保存确认</span><strong>${r.saved?'已保存':'未确认'}</strong></div><div><span>长期资格</span><strong>${r.ready?'已就绪':'未就绪'}</strong></div></div>`;
  if(r.missing?.length)html+=`<p class="notice-inline">缺失来源：${escapeHTML(r.missing.join('、'))}。没有静默缩小所选范围。</p>`;
  if(r.items?.some(i=>i.conflict))html+='<p class="notice-inline">独立有效来源存在未裁决冲突，以下分歧完整保留。</p>';
  for(const item of r.items||[])html+=`<article class="context-item ${item.conflict?'conflict':''}"><small>${escapeHTML(item.memory_id)} · v${item.version} · ${escapeHTML(tiers[item.tier]||'')}层</small><p>${escapeHTML(item.text)}</p><small>来源：${escapeHTML(item.source)}</small></article>`;
  if(r.budget!==undefined)html+=`<p class="small-note">装入 ${r.used} / ${r.budget} 模拟字符 · 因整组预算省略 ${r.omitted} 条。正式tokenizer预算另验。</p>`;
  if(r.artifact)html+=`<article class="context-item"><small>核验后的派生候选 · ${escapeHTML(r.artifact.classification)}</small><p>${escapeHTML(r.artifact.text)}</p><small>${escapeHTML(r.artifact.source)} · 来源版本 ${r.artifact.source_version}</small></article>`;
  if(r.candidate)html+=`<p class="notice-inline">被拒绝候选：${escapeHTML(r.candidate)}<br>原来源：${escapeHTML(r.source)}</p>`;
  if(r.design_note)html+=`<p class="small-note">${escapeHTML(r.design_note)}</p>`;
  if(r.action)html+=`<p class="notice-inline">${escapeHTML(r.action.id)} · ${tiers[r.action.from]}→${tiers[r.action.to]} · ${escapeHTML(label(r.action.status))}</p>`;
  if(r.actions)html+=r.actions.map(a=>`<p>${escapeHTML(a.id)} · ${tiers[a.from]}→${tiers[a.to]} ${badge(a.status)}</p>`).join('');
  html+=`<details><summary>查看模拟输入输出字段</summary><pre>${escapeHTML(JSON.stringify(r,null,2))}</pre></details>`;return html;
}
function renderStory(){const s=scene();$('scene-list').innerHTML=scenes.map(x=>`<button class="scene-button ${x.id===currentId?'selected':''}" data-scene="${x.id}"><b>${x.id.slice(1)}</b><span><strong>${escapeHTML(x.title)}</strong><small>${escapeHTML(x.sub)}</small></span></button>`).join('');
  $('scene-heading').innerHTML=`<div class="scene-heading"><p class="eyebrow">${s.id} / ${escapeHTML(s.phase)} · ${s.steps.length}步</p><h2>${escapeHTML(s.title)}</h2><p class="muted">${escapeHTML(s.sub)}</p><div class="tags">${s.fr.map(fr=>`<span class="badge">${fr}</span>`).join('')}${s.adr.map(id=>`<button class="badge" data-decision="${id}">${id} ↗</button>`).join('')}</div></div>`;
  $('progress').innerHTML=s.steps.map((_,i)=>`<i class="${i<cursor?'done':i===cursor?'current':''}"></i>`).join('');const next=s.steps[cursor];$('step-count').textContent=next?`${cursor+1} / ${s.steps.length} · 下一步`:'本专题走查完成';$('step-title').textContent=next?.title||'查看过程证据，或继续自由试用';$('step-help').textContent=next?.explain||'所有结果均为模拟，可按trace_id查看每个节点；切换专题保留当前进度。';$('next').disabled=!next;$('next').textContent=next?'执行这一步 →':'已完成 ✓';$('result-status').className='badge '+color(model.last?.status);$('result-status').textContent=label(model.last?.status||'尚未操作');$('result').innerHTML=resultHTML(model.last);
  $('actor').value=model.actor;$('tenant').value=model.requestTenant;$('credential').value=model.credential;
  $('memory').innerHTML=model.memories.filter(m=>m.state==='active').map(m=>`<option value="${m.id}">${m.id} · v${m.version} · ${escapeHTML(m.tenant)}</option>`).join('')||'<option value="">暂无有效记忆</option>';$('memory').value=model.lastMemory||'';
  $('state').innerHTML=`<div class="state-body"><div class="state-summary">当前调用方：${escapeHTML(model.actors[model.actor].name)}<br>公司A：${badge(model.tenants.A.enabled?'active':'blocked')} · 配置v${model.tenants.A.revision}<br>虚拟时钟 ${model.now}s · 共享许可 ${model.grants.filter(g=>g.active&&g.expires>model.now).length} 条<br>任务 ${model.tasks.length} · 待确认事件 ${model.outbox.filter(e=>e.status!=='acked').length} · 动作 ${model.actions.length}</div>${model.memories.slice().reverse().map(m=>`<article class="state-object ${m.state!=='active'?'retired':''}"><h4>${escapeHTML(m.id)} / v${m.version} ${badge(m.state)}</h4><p>${escapeHTML(m.text)}</p><div class="state-row"><span>归属 / 主体</span><span>${m.tenant} / ${m.owner}</span></div><div class="state-row"><span>类型 / 长期资格</span><span>${m.kind} / ${escapeHTML(label(m.projection))}</span></div><div class="state-row"><span>确认层 / 清理</span><span>${tiers[m.tier]} / ${escapeHTML(label(m.cleanup==='none'?'无待办':m.cleanup))}</span></div></article>`).join('')||'<p class="empty">尚未保存模拟内容</p>'}</div>`;
}
function renderTrace(){const ids=[...new Set(model.spans.map(s=>s.trace_id))];if(selectedTrace!=='all'&&!ids.includes(selectedTrace))selectedTrace='all';$('trace-select').innerHTML='<option value="all">全部关联过程</option>'+ids.map(id=>`<option value="${id}">${id}</option>`).join('');$('trace-select').value=selectedTrace;const search=$('trace-search').value.trim().toLowerCase();const spans=model.spans.filter(s=>(selectedTrace==='all'||s.trace_id===selectedTrace)&&(!search||JSON.stringify(s).toLowerCase().includes(search)));
  $('trace-summary').innerHTML=`<span>${spans.length} 个节点</span><span>${spans.filter(s=>['failed','denied','blocked','unknown'].includes(s.status)).length} 个失败 / 阻断 / 未知节点</span><span>输入与输出均为样例，无真实凭证</span>`;
  $('timeline').innerHTML=spans.map(s=>`<article class="timeline-entry"><div class="timeline-time">虚拟时间 ${s.time}s<br>${escapeHTML(s.owner)}<br>${escapeHTML(s.span_id)}</div><div class="timeline-content ${color(s.status)==='bad'?'bad':''}"><h3>${escapeHTML(s.stage)} ${badge(s.status)}</h3>${traceButton(s.trace_id)}${s.reason?`<p class="notice-inline">原因：${escapeHTML(s.reason)}</p>`:''}<details><summary>输入、输出与关联字段</summary><div class="io-grid"><div><p class="small-note">输入</p><pre>${escapeHTML(JSON.stringify(s.input,null,2))}</pre></div><div><p class="small-note">输出</p><pre>${escapeHTML(JSON.stringify(s.output,null,2))}</pre></div></div></details></div></article>`).join('')||'<div class="empty">暂无匹配记录，先执行业务步骤。</div>';
}
function table(title,headers,rows){return `<div class="card table-wrap"><h3>${title}</h3><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">暂无记录</td></tr>`}</tbody></table></div>`;}
function renderOps(){
  $('health').innerHTML=Object.entries(model.health).map(([name,ok])=>`<article class="health-card"><h3>${names[name]} ${badge(ok?'healthy':'failed')}</h3><p>${ok?'当前模拟依赖可用':'依赖不可用，查看受影响任务及调用'}</p><button data-health="${name}">${ok?'模拟不可用':'恢复依赖'}</button></article>`).join('');$('fault').value=model.fault;$('ops-result').innerHTML=model.last?`<div class="card">${resultHTML(model.last)}</div>`:'';
  $('operations').innerHTML=table('任务与恢复记录',['任务 / 归属','状态与租约','错误与恢复判定','关联'],model.tasks.map(t=>`<tr><td>${escapeHTML(t.id)}<br>${t.tenant}/${t.actor}<br>${escapeHTML(t.memory_id)} v${t.version}</td><td>${badge(t.status)}<br>尝试 ${t.attempts} · 代次 ${t.fence}<br>租约至 ${t.lease}s</td><td>${escapeHTML(t.error||'—')}<br>${t.recovery.map(r=>escapeHTML(r.decision+' @'+r.at+'s')).join('<br>')}</td><td>${traceButton(t.trace_id)}</td></tr>`))+
    table('可靠事件交接',['事件','对象与版本','投递','消费结果'],model.outbox.map(e=>`<tr><td>${escapeHTML(e.id)}<br>${escapeHTML(e.type)}</td><td>${escapeHTML(e.memory_id)} v${e.version}</td><td>${badge(e.status)}<br>尝试 ${e.delivery_attempts}</td><td>${e.consumer_applied?'已生效，重投去重':'尚未生效'}<br>${traceButton(e.trace_id)}</td></tr>`))+
    table('内部自动调度',['原动作','目标','执行观察','关联'],model.actions.map(a=>`<tr><td>${escapeHTML(a.id)}<br>${escapeHTML(a.memory_id)} v${a.version}</td><td>${tiers[a.from]}→${tiers[a.to]}<br>${escapeHTML(a.reason)}</td><td>${badge(a.status)}<br>模拟端：${escapeHTML(a.provider)}</td><td>${traceButton(a.trace_id)}</td></tr>`))+
    table('受控配置操作记录',['操作','结果','版本','关联'],model.audit.map(a=>`<tr><td>${escapeHTML(a.operation)}</td><td>${escapeHTML(a.result)}</td><td>${a.tenant_revision||'未生效'}</td><td>${a.trace_id?traceButton(a.trace_id):'配置失败未改变版本'}</td></tr>`));
}
const requirementNames=['保存事件与任务','当前任务记忆','长文与文档加工','分类与生命周期','事实形成与更正','提纯压缩与质量','长期检索就绪','来源选择与查询','排序去重与冲突','上下文交付与预算','处理查询与再次获取','存储与召回轨迹','基础调度规则','执行与结果确认','租户与授权','预测与预热','删除与阻断','运行与恢复'];
function renderDesign(){
  $('decisions').innerHTML=decisions.map(d=>`<article id="decision-${d[0]}" class="card"><span class="badge">${d[0]} · Proposed</span><h3>${escapeHTML(d[1])}</h3><p>${escapeHTML(d[2])}</p><p class="muted">代价与边界：${escapeHTML(d[3])}</p><a href="../ADR版本/ADR-P2P3-001_总体架构决策.md#${d[0].toLowerCase()}">对应主ADR ↗</a><div class="tags">${scenes.filter(s=>s.adr.includes(d[0])).map(s=>`<button data-scene="${s.id}" class="badge">${s.id}</button>`).join('')}</div></article>`).join('');
  $('coverage').innerHTML=requirementNames.map((name,i)=>{const fr='FR'+String(i+1).padStart(2,'0'),related=scenes.filter(s=>s.fr.includes(fr));return `<tr><td>${fr}</td><td>${name}</td><td>${related.map(s=>`<button class="badge" data-scene="${s.id}">${s.id}</button>`).join(' ')}</td><td>${[...new Set(related.flatMap(s=>s.adr))].join(' / ')}</td><td>${fr==='FR16'?'后续P1目标模拟':fr==='FR06'?'质量拒绝与合格产物模拟；压缩质量需实测':fr==='FR15'?'业务规则模拟；真实身份与P2隔离另验':fr==='FR18'?'状态化故障与恢复模拟；持久性和长稳另验':'已提供目标行为模拟；真实依赖与结果另验'}</td></tr>`;}).join('');
  $('tenant-coverage').innerHTML=[['合法接入 / 未绑定','S09','映射、未绑定拒绝、配置失败不部分开通'],['跨租户 / 伪造编号','S09','请求范围、原任务编号及结果均按当前主体核验'],['同租户共享 / 操作权限','S09','共享可读，不可删除'],['撤权 / 旧结果 / 在途交付','S01','候选已形成后撤权，最终交付仍阻断'],['停用 / 后台 / 旧配置恢复','S11','旧快照恢复不能复活当前失效许可'],['外部撤销 / P2多路径隔离','S09','示例传播时间线；真实身份及P2隔离不由Mock证明']].map(([t,s,d])=>`<p><button class="badge" data-scene="${s}">${s}</button> <strong>${t}</strong> · ${d}</p>`).join('');
}
function render(){renderStory();renderOps();renderTrace();renderDesign();document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!=='view-'+view);document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('selected',el.dataset.view===view));$('storage-note').textContent=storageOK?'浏览器当前标签内保留模拟进度；重置只清空当前专题。正文均为演示样例。':'浏览器禁用会话存储，当前页面仍可演示；刷新后重新开始。';}
function changeView(name){view=name;render();window.scrollTo({top:0,behavior:'instant'});}
function runCommand(name){const options={sources:$('sources').value,query:$('query').value,budget:Number($('budget').value)};const commands={write:()=>model.remember($('text').value),recall:()=>model.recall(options),correct:()=>model.mutate('correct',$('text').value),delete:()=>model.mutate('delete'),replay:()=>model.replay(),pause:()=>model.recall({...options,pause:true}),finish:()=>model.finishPending(),process:()=>model.process(),advance:()=>model.advance(),recover:()=>model.recover(),reconcile:()=>model.reconcile(),probe:()=>model.probe(),backup:()=>model.backup(),restore:()=>model.restore(),crash:()=>{model.fault='crash';model.process();}};commands[name]?.();save();render();}
function exportRecord(){const payload={format:'aether-p3-review-v2',prd:'V1.3',adr:'ADR-P2P3-001 / D01—D08 / Proposed',mode:'simulated',scenario:currentId,steps_completed:cursor,notice:'模拟过程记录，不是产品验收、真实模型或P2运行证据。',state:model.state()};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`aether-mock-V1.3-${currentId}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.dataset.view){changeView(b.dataset.view);return;}
  if(b.dataset.scene){if(currentId===b.dataset.scene){changeView('story');}else location.hash='scenario='+b.dataset.scene;return;}
  if(b.dataset.trace){selectedTrace=b.dataset.trace;changeView('trace');return;}
  if(b.dataset.decision){changeView('design');$('decision-'+b.dataset.decision)?.scrollIntoView({behavior:'smooth',block:'center'});return;}
  if(b.dataset.command){runCommand(b.dataset.command);return;}
  if(b.dataset.config){model.configure(b.dataset.config);save();render();return;}
  if(b.dataset.health){model.health[b.dataset.health]=!model.health[b.dataset.health];model.probe();save();render();return;}
  if(b.hasAttribute('data-export'))exportRecord();
});
$('next').onclick=()=>{const s=scene().steps[cursor];if(!s)return;s.act(model,context);cursor++;save();render();};$('reset').onclick=()=>load(currentId,true);
$('actor').onchange=()=>{model.select($('actor').value);save();render();};$('tenant').onchange=()=>{model.requestTenant=$('tenant').value;save();};$('credential').onchange=()=>{model.credential=$('credential').value;save();};$('memory').onchange=()=>{model.lastMemory=$('memory').value;const t=model.tasks.filter(t=>t.memory_id===model.lastMemory).at(-1);if(t)model.lastTask=t.id;save();};$('fault').onchange=()=>{model.fault=$('fault').value;save();};$('trace-select').onchange=()=>{selectedTrace=$('trace-select').value;renderTrace();};$('trace-search').oninput=renderTrace;
function route(){const id=new URLSearchParams(location.hash.slice(1)).get('scenario')||'S01';load(id);}window.addEventListener('hashchange',route);route();
