/* One scenario catalog for the complete PRD review. Functions use the same simulator. */
(function(root){
  const step=(title,explain,act)=>({title,explain,act});
  const seed=(m,text='项目预算上限20万元，每周五汇报。',kind='working')=>{m.remember(text,{kind});m.process();};
  const scene=(id,title,sub,fr,adr,setup,steps,phase='MVP')=>({id,title,sub,fr,adr,setup,steps,phase});
  const scenes=[
    scene('S01','完整业务主线','保存 → 使用 → 共享 → 更正 → 撤权 → 恢复',['FR01','FR02','FR05','FR07','FR11','FR15','FR18'],['D01','D02','D03','D06','D07'],()=>{},[
      step('A1保存项目约束','同一条预算记忆贯穿本场景；返回已保存，不假报长期就绪。',m=>m.remember()),
      step('立即使用当前记忆','后台加工未完成，Working可独立使用。',m=>m.recall({sources:'working'})),
      step('后台加工并核验长期资格','演示候选、来源、准确回读与投影核验。',m=>m.process()),
      step('新会话使用长期记忆','交付来源与版本；实际访问进入内部调度。',m=>m.recall({sources:'long_term'})),
      step('A2尝试读取私有内容','同租户不自动共享。',m=>{m.select('a2');m.recall();}),
      step('受控授予只读共享','仅开放目标记忆的读取权限。',m=>m.configure('grant')),
      step('A2通过统一Recall使用共享内容','共享候选与本人候选遵守同一最终资格检查。',(m,c)=>{m.recall();c.shared=m.lastContext;}),
      step('A2尝试删除','只读共享不能扩大成写权限。',m=>m.mutate('delete')),
      step('A1更正预算为15万元','新版本生效，旧索引留存也不能作为当前事实。',m=>{m.select('a1');m.mutate('correct','项目预算上限15万元，每周五汇报。');}),
      step('重新使用当前预算','只能交付当前15万元的版本。',m=>m.recall()),
      step('A2重新获取更正前结果','旧结果版本失效，不重新交付20万元。',(m,c)=>{m.select('a2');m.replay(c.shared);}),
      step('A2检索后暂停在最终交付前','候选存在，但正文尚未交付。',m=>m.recall({pause:true})),
      step('撤销共享','受控变更发生在请求处理中。',m=>m.configure('revoke')),
      step('继续最终交付','当前授权复核失败，旧候选被阻断。',m=>m.finishPending()),
      step('保存模拟业务快照','快照包含旧数据状态；当前授权配置独立保留。',m=>{m.select('a1');m.backup();}),
      step('停用公司A','已有数据保留，新增使用和失效后台提交受阻。',m=>m.configure('disable')),
      step('恢复旧业务快照','用当前受控配置核验，不复活已停用租户。',m=>m.restore()),
      step('检查恢复后的后台任务','原任务不能沿用已失效许可提交。',m=>m.process()),
      step('核对已经发生的调度','维护侧可核对已有外部效果，不伪造用户授权。',m=>m.reconcile()),
      step('查看运行检测','健康与业务资格分开：进程可用不代表停用租户有权限。',m=>m.probe())
    ]),
    scene('S02','更正与历史结果','旧索引、原结果与当前版本',['FR05','FR07','FR11'],['D02','D03'],seed,[
      step('先取得20万元上下文','保留原结果编号。',(m,c)=>{m.recall();c.old=m.lastContext;}),
      step('显式更正为15万元','旧版留作历史，新版需重新取得长期资格。',m=>m.mutate('correct','项目预算上限15万元。')),
      step('读取当前记忆','不能继续返回旧预算。',m=>m.recall()),
      step('尝试重新获取旧结果','不能只把历史缓存原样返回。',(m,c)=>m.replay(c.old)),
      step('加工新版并跨会话读取','准确版本投影通过才允许长期召回。',m=>{m.process();m.recall({sources:'long_term'});})
    ]),
    scene('S03','可靠保存与事件交接','重复输入、确认丢失和原事件重投',['FR01','FR12','FR18'],['D02','D06','D07'],m=>{m.deliveryPaused=true;},[
      step('暂停投递后保存','事实、任务和Outbox都已登记，消费方尚未收到。',m=>m.remember('项目预算20万元。',{key:'fixed'})),
      step('同键同内容重复保存','不创建第二份正式事实。',m=>m.remember('项目预算20万元。',{key:'fixed'})),
      step('同键不同内容','拒绝把原操作覆盖成别的内容。',m=>m.remember('项目预算15万元。',{key:'fixed'})),
      step('消费成功但丢失确认','保持待确认记录，消费业务效果已保存。',m=>m.flush(true)),
      step('重投原事件','消费者去重，不重复计热或生成业务效果。',m=>m.flush()),
      step('完成同一加工任务','恢复事件交接后仍用原任务身份。',m=>{m.deliveryPaused=false;m.process();})
    ]),
    scene('S04','召回与来源故障','完整、空、降级、不可用',['FR08','FR10'],['D03','D05'],seed,[
      step('当前与长期来源正常','只返回有效且获准的正文、来源和版本。',m=>m.recall()),
      step('模拟长期检索不可用','当前来源独立可用，返回降级及缺失来源。',m=>{m.health.vector=false;m.recall();}),
      step('明确只选长期来源','不擅自用Working冒充所选来源完整成功。',m=>m.recall({sources:'long_term'})),
      step('依赖恢复但没有匹配材料','来源正常无匹配才是正常空。',m=>{m.health.vector=true;m.recall({query:'火星气象'});}),
      step('正文服务不可用','候选存在也不能伪造正文或报正常空。',m=>{m.health.object=false;m.recall();}),
      step('依赖恢复后重新调用','新请求重新取得可用材料。',m=>{m.health.object=true;m.recall();})
    ]),
    scene('S05','删除与迟到加工','先阻断使用，再核对清理',['FR11','FR17'],['D02','D03','D07'],seed,[
      step('保存原Context','后续验证历史结果也受删除约束。',(m,c)=>{m.recall();c.old=m.lastContext;}),
      step('删除目标记忆','旧版本、当前版本都退出使用资格。',m=>m.mutate('delete')),
      step('新请求不再返回正文','来源正常、无合格内容，返回正常空。',m=>m.recall()),
      step('重新获取旧Context','失效正文不可再次交付。',(m,c)=>m.replay(c.old)),
      step('旧加工任务迟到','不能使已删除记忆重新就绪。',m=>m.process()),
      step('核验派生内容清理','对象、投影和副本清理与使用阻断分别表达。',m=>m.cleanup())
    ]),
    scene('S06','自动调度与反馈','升降层、容量、失败与Unknown',['FR12','FR13','FR14'],['D05','D06'],seed,[
      step('第一次实际访问','事件自动进入策略；调用者不提交调度业务请求。',m=>m.recall()),
      step('第二次访问，执行成功但丢回执','示例热度规则触发温→热；先保留Unknown和原读取路径。',m=>{m.fault='ack';m.recall();}),
      step('按原动作查询结果','无新动作，核对目标后收敛到成功。',m=>{m.fault='none';m.reconcile();}),
      step('后续读取使用已确认层级','业务类型与事实版本保持独立。',m=>m.recall()),
      step('模拟访问衰减，周期降层','按相邻规则热→温，不改变原文事实。',m=>m.schedule('down')),
      step('模拟容量不足','暂缓新动作，保留可读状态。',m=>{m.fault='capacity';m.schedule('up');}),
      step('执行端明确失败','失败有证据；不把失败伪装成未知或成功。',m=>{m.fault='executor_fail';m.schedule('up');}),
      step('新的评估中执行端丢失历史证据','不能假定动作未执行。',m=>{m.fault='evidence_lost';m.schedule('up');}),
      step('对账仍无证据','继续Unknown，不重发冲突动作。',m=>{m.fault='none';m.reconcile();}),
      step('停用租户后核对已有动作','不能生成新的用户业务动作；允许受控核对旧效果。',m=>{m.configure('disable');m.reconcile();})
    ]),
    scene('S07','P2交接与准确版本','正文、向量、来源和执行证据',['FR01','FR07','FR08','FR14'],['D01','D05'],()=>{},[
      step('保存带来源的预算','P3维护业务身份，P2对象替身提供内容。',m=>m.remember()),
      step('投影与准确回读','查看同一trace_id中的来源、版本和就绪判断。',m=>m.process()),
      step('消费长期候选','P2候选不能直接当最终Context。',m=>m.recall({sources:'long_term'})),
      step('P2依赖失败','能力不可用时结果明确，不假装完整交付。',m=>{m.health.vector=false;m.recall({sources:'long_term'});})
    ]),
    scene('S08','冲突与完整预算','独立有效来源保留分歧',['FR09','FR10'],['D03'],m=>{seed(m,'项目预算20万元。');seed(m,'项目预算15万元。');seed(m,'每周五汇报。');},[
      step('完整保留两个预算来源','未经明确更正，不能自动删除其中一个观点。',m=>m.recall({budget:400})),
      step('首组放不下，尝试后组','预算为模拟字符；跳过整个冲突组，保留可装入的汇报安排。',m=>m.recall({budget:45})),
      step('所有组都放不下','返回不可用及原因，不切断否定、数字或冲突另一侧。',m=>m.recall({budget:3})),
      step('恢复足够预算','可观察省略数量和完整来源。',m=>m.recall({budget:400}))
    ]),
    scene('S09','租户、共享与撤权','PRD 12.8六组行为走查',['FR15','FR11','FR18'],['D03','D07'],seed,[
      step('合法映射的A1读取','认证、业务开通、资源许可分别判断。',m=>m.recall()),
      step('已认证但未绑定','不能自动开通或访问业务数据。',m=>{m.select('unbound');m.recall();}),
      step('无效配置整批拒绝','缺少身份来源时不能部分开通。',m=>m.configure('invalid')),
      step('受控开通映射','维护侧配置身份映射，不新增产品登录后台。',m=>m.configure('bind')),
      step('映射成功仍无资源许可','业务开通不等于可读同租户所有记忆。',m=>m.recall()),
      step('A1伪造B请求范围','请求tenant字段不能扩大权限。',m=>{m.select('a1','B');m.recall();}),
      step('B主体直接查询A任务编号','任务和结果查询同样隔离，不返回敏感存在信息。',m=>{m.select('b1');m.queryTask();}),
      step('A2读取私有内容','同租户不同主体需要共享授权。',m=>{m.select('a2');m.recall();}),
      step('授予只读共享','共享包含对象、操作、有效期和版本。',m=>m.configure('grant')),
      step('A2检索共享并保留Context','共享候选发现与最终核验是一条Recall路径。',(m,c)=>{m.recall();c.shared=m.lastContext;}),
      step('A2尝试删除','读取权不包含删除权。',m=>m.mutate('delete')),
      step('A2检索后暂停','模拟在途请求，尚未向调用者交付正文。',m=>m.recall({pause:true})),
      step('撤销共享并恢复在途请求','最终交付重新检查当前授权。',m=>{m.configure('revoke');m.finishPending();}),
      step('再次获取原结果','旧结果编号不能绕过撤权。',(m,c)=>m.replay(c.shared)),
      step('改显示名称','租户A的稳定编号和资源归属保持不变。',m=>m.configure('rename')),
      step('停用A1主体','主体停用影响后续访问；不假装删除数据。',m=>{m.select('a1');m.configure('disable_subject');m.recall();}),
      step('重新启用主体并模拟外部撤销','外部撤销与本地共享撤销不同；示例传播窗口30秒。',m=>{m.configure('enable_subject');m.configure('external_revoke');}),
      step('窗口内的既有有效凭证','本示例选择到期检测，不承诺瞬间撤销所有凭证。',m=>m.recall()),
      step('推进时钟并再次访问','传播窗口后必须阻断；正式窗口在联调前确认。',m=>{m.advance(40);m.recall();})
    ]),
    scene('S10','文档加工与生命周期','候选、质量拒绝、来源与归档',['FR03','FR04','FR05','FR06','FR07'],['D02','D04'],()=>{},[
      step('保存带版本的文档样例','使用预设文本代替真实上传、解析和模型。',m=>m.remember('会议第1节：预算20万元。第2节：不得取消周五汇报。',{kind:'episodic',source:'会议纪要@v1/第1—2节'})),
      step('模拟提取模型不可用','已保存与加工失败分开。',m=>{m.health.model=false;m.process();}),
      step('候选改变数字和否定','来源质量检查拒绝发布。',m=>{m.health.model=true;m.fault='quality';m.process();}),
      step('合格候选通过并长期就绪','保留数字、否定与来源；不展示虚构压缩率。',m=>{m.fault='none';m.process();}),
      step('使用文档派生内容','来源和版本与输入绑定。',m=>m.recall({sources:'long_term'})),
      step('归档该记忆','退出默认召回，内容不等于被删除。',m=>m.mutate('archive')),
      step('默认查询不包含归档内容','生命周期影响资格。',m=>m.recall()),
      step('重新激活并核验','恢复资格不绕过当前授权及版本。',m=>{m.mutate('reactivate');m.recall();})
    ]),
    scene('S11','追踪、检测与恢复','Worker中断、租约与旧配置恢复',['FR15','FR18'],['D02','D06','D07'],()=>{},[
      step('保存事实与持久任务','记下本次trace_id；加工和恢复继续关联原请求。',m=>m.remember()),
      step('加工途中Worker退出','持久任务保留运行状态，不能假装失败后什么都没做。',m=>{m.fault='crash';m.process();}),
      step('检测Worker不可用','探测失败不等于自动重启或业务已恢复。',m=>m.probe()),
      step('推进到租约过期并扫描','检测记录指出原任务及恢复判定入口。',m=>{m.advance(20);m.probe();}),
      step('恢复服务并重新核验原任务','当前授权及版本有效才重排；沿用原任务身份。',m=>m.recover()),
      step('原任务再次处理','新的领取代次完成投影，正式记忆没有重复。',m=>m.process()),
      step('旧Worker迟到返回','失效租约代次被拒绝，不能覆盖新结果。',m=>m.lateCommit()),
      step('保存业务快照','用于演示停用后的旧数据恢复。',m=>m.backup()),
      step('产生新版待办，再停用A','业务记录存在不代表还允许后台执行。',m=>{m.mutate('correct','项目预算15万元。');m.configure('disable');}),
      step('尝试旧任务提交','根据当前停用状态阻断。',m=>m.process()),
      step('恢复旧快照','当前受控配置仍保持停用，旧许可不能复活。',m=>m.restore()),
      step('恢复后再读仍拒绝','业务恢复不等于授权恢复。',m=>m.recall()),
      step('受控启用后再核验内容','启用不复活已被更正的旧正文；需要重新准备当前版本。',m=>{m.configure('enable');m.recall();})
    ]),
    scene('S12','预测预热 · 后续阶段','先准备、后访问，失败可回退',['FR16'],['D06','D08'],seed,[
      step('预测未来访问并准备','模拟预测在实际访问前发生；独立预热预算。',m=>m.forecast()),
      step('随后发生实际访问','观察实际状态，不用模拟数字宣称性能收益。',m=>m.recall()),
      step('预测能力失效','回退基础策略，不影响当前任务读取。',m=>{m.fault='forecast';m.forecast();}),
      step('正常Recall继续','预测失败不能拖垮基础业务。',m=>m.recall())
    ],'后续 P1')
  ];
  const decisions=[
    ['D01','三流程与公共基础','Remember负责事实；Recall负责一次上下文；Operate持续调整访问准备。两个对外功能，逻辑模块不等于三个微服务。','拆分接口增加协作成本，以统一类型、事件和验收场景控制。'],
    ['D02','事实、派生与就绪','保存和长期可检索分开。版本、更正、删除及来源由Remember管理，旧任务不能恢复失效内容。','异步状态更多，需要可靠待办和最终资格核验。'],
    ['D03','可信上下文流水线','候选、正文、当前授权、版本、冲突组和预算依次核验；再次获取原结果仍复核。','多一次检查换取当前有效性，不能把相似TopK直接当上下文。'],
    ['D04','框架采用边界','LangMem局部提取适配；LlamaIndex参考检索分层；Controller参考控制循环。模型和存储并未在Mock运行。','维护适配器与自身业务契约，正式采用需质量和失败实验。'],
    ['D05','Provider与P2交接','P2提供正文、向量、关系与执行证据；P3保留业务资格。模拟DTO不是正式RPC协议。','精确版本、过滤与路由证据需双方冻结并实测。'],
    ['D06','持续核对原动作','根据当前状态计算差异，实际效果未知就查询原动作；受理不等于生效。','需要状态观察与幂等；证据丢失可能长期Unknown。'],
    ['D07','授权、追踪与恢复','身份映射、共享、停用和当前许可贯穿前后台。Trace定位过程；任务、事件和动作事实决定恢复。','受控配置及恢复规则要跨模块一致；外部撤销窗口需要约定。'],
    ['D08','阶段与证据','本页只确认产品行为；真实依赖、质量、持久化与24/72小时稳定性另验。预测预热属后续P1。','需求和模拟证据不能代替联合验收，主ADR仍为Proposed。']
  ];
  const api={scenes,decisions};if(typeof module!=='undefined')module.exports=api;else root.P3ReviewContent=api;
})(typeof window!=='undefined'?window:globalThis);
