[mypy]
python_version = 3.13
strict = True
follow_imports = silent
plugins = pydantic.mypy
mypy_path = src

[mypy-sentence_transformers.*]
follow_imports = skip
ignore_missing_imports = True

[mypy-pymilvus.*]
follow_imports = skip
ignore_missing_imports = True

[mypy-fastembed.*,torch.*,transformers.*,onnxruntime.*,tokenizers.*,numpy.*,pandas.*,scipy.*,sklearn.*,huggingface_hub.*,tiktoken.*]
follow_imports = skip
ignore_missing_imports = True
