"""Prepare public model, tokenizer and Linux Temporal assets outside the checkout.

The team supplies its public Milvus CA separately. Credentials are never
downloaded or generated by this script. Use a new, external directory.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

MODEL_NAME = "BAAI/bge-small-zh-v1.5"


def download_model(target: Path) -> None:
    from fastembed import TextEmbedding

    definition = TextEmbedding._get_model_description(MODEL_NAME)
    # HF appends its repo/snapshot path. A deep output path exceeds Windows MAX_PATH.
    with tempfile.TemporaryDirectory(prefix="p3-model-") as cache:
        source = TextEmbedding.download_model(definition, cache_dir=cache)
        shutil.copytree(source, target)


def download_temporal(target: Path) -> None:
    subprocess.run(
        [sys.executable, "-B", str(Path(__file__).with_name("install_temporal_cli.py")),
         "--directory", str(target.parent), "--target-platform", "Linux"],
        check=True,
    )


def download_tokenizers(target: Path) -> None:
    import tiktoken

    target.mkdir()
    previous = os.environ.get("TIKTOKEN_CACHE_DIR")
    os.environ["TIKTOKEN_CACHE_DIR"] = str(target)
    try:
        for name in ("cl100k_base", "o200k_base"):
            tiktoken.get_encoding(name)
    finally:
        if previous is None:
            os.environ.pop("TIKTOKEN_CACHE_DIR", None)
        else:
            os.environ["TIKTOKEN_CACHE_DIR"] = previous


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", required=True, type=Path)
    args = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[2]
    repository = next((p for p in (root, *root.parents) if (p / ".git").exists()), root)
    directory = args.directory.expanduser().resolve()
    if directory == repository or repository in directory.parents:
        parser.error("test assets must live outside the repository")
    if directory.exists():
        parser.error("asset directory already exists; choose a new external directory")
    directory.mkdir(parents=True, exist_ok=False)
    download_model(directory / "model")
    download_temporal(directory / "temporal")
    download_tokenizers(directory / "tiktoken")
    native = {
        "backend": "onnx", "model_name": MODEL_NAME,
        "model_path": str(directory / "model"),
        "cache_dir": str(directory / "embedding-cache"),
        "precision": "fp32", "threads": 2,
    }
    with (directory / "native.json").open("x", encoding="utf-8") as output:
        json.dump(native, output, indent=2)
    print("Public AKS assets prepared:", directory)
    print("Add the team's public Milvus CA as milvus-ca.crt before running AKS tests.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
